jobs:
  include:
  - os: linux
    dist: trusty
  - os: osx
branches:
  only:
  - develop
  - master
language: c
script: bash -ex .travis-ci.sh
env:
  matrix:
  - OCAML_VERSION=4.04.0 OPAM_VERSION=1.2.2
after_success: bash -ex .deploy.sh
deploy:
  provider: releases
  file: bin/kind2
  tag_name: nightly-${TRAVIS_OS_NAME}
  cleanup: false
  on:
    all_branches: true
  api_key: ${API_KEY}
