jobs:
  include:
  - os: linux
    dist: trusty
  - os: osx
language: c
script: bash -ex .travis-ci.sh
env:
  matrix:
  - OCAML_VERSION=4.04.0 OPAM_VERSION=1.2.2
after_success: bash -ex .deploy.sh
deploy:
  provider: releases
  token:
    secure: VZu7Clnw63x21hwNSkmkFi6Hs6GKRY0HwqRpkaHUF8nEafeKbY/YysnYfmIE9QdHzPfu7pih4hcdA24GD5vJ9RzjeiieZZwrQAgYSzfRxzNqLbG0cQzC8zEXrN1uow8I1VHEMsPRo5uSLd5cAorh4SUwecGF9tCK+F6gWsv1c8WcxWq298N9LbgUHVYgEmuYtYBoXKWOdsKe9YErvERHeey2QInGdCngsX6k3dd/5NM5Nzz4qMWaXnTVBnhuP8o/BA+0EXExjFWjD29bSBVdt+urYnKDhmBS75aABgGaF2Y4nuRClyiwLA2lLtM8bU8pcvWZc6FYSH3nchbNXyK4yq2c7JwWcID0HozqEh14wxcBze3w/zsTSnQHD/t1RbarSkJvyLMnUZ27UXq6Bzm7Z4nLsh8V7iyRwRu/1MvVHAFF6GRShEf7tuwYDgRzIiLIfTJDncX6uacEh1Yrj/AI/wwU1zzWFjbm8+zn8aqlUCNX1xpMomKXnL2i4wr3klo262Z4d/ESw3O55w8gYVdTSx5yCmTH2SJD7bGQgpdlQqarV/sDWWgWQ00T9+3TrBoJhK3/7JtzRe0MF7XRMZ4FRWDertUXil0Jq0Jj2Bi/Bvri/KXfE7C/K941XB9L4PnujW9wzbYYgFba7Da28xo3lIyAX88bl6wBqxj0TbuezVI=
  file: "/usr/local/bin/kind2"
  tag_name: nightly
  overwrite: true
  skip_cleanup: true
  on:
    branches:
      only:
      - develop
      - master
      - nightly
